# Generated by Django 4.0.1 on 2022-01-19 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='vtes',
            new_name='votes',
        ),
    ]
